import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

export function LegalDisclaimer() {
  return (
    <Accordion type="single" collapsible className="w-full">
      <AccordionItem value="item-1">
        <AccordionTrigger>Legal Disclaimer</AccordionTrigger>
        <AccordionContent>
          <p className="text-sm text-muted-foreground">
            This Failure Finding Interval (FFI) Calculator is provided for informational purposes only. By using this tool, you agree to the following
            terms:
          </p>
          <ul className="list-disc list-inside text-sm text-muted-foreground mt-2 space-y-2">
            <li>The results generated by this tool should not replace professional engineering judgment or analysis.</li>
            <li>The user is fully responsible for any decisions or actions taken based on the outputs of this tool.</li>
            <li>
              The developers and owners of this tool shall not be held liable for any damages or losses arising from the use of or reliance on this
              tool.
            </li>
            <li>While we strive for accuracy, we cannot guarantee the completeness or accuracy of the tool&apos;s outputs.</li>
            <li>This tool is provided &apos;as-is&apos; without any warranties, either express or implied.</li>
            <li>Always consult with qualified professionals before making critical decisions related to equipment maintenance and safety.</li>
          </ul>
        </AccordionContent>
      </AccordionItem>
    </Accordion>
  );
}
