import { Question, Answer, Asset } from "../types/rcm";

export const questions: Record<string, Question> = {
  Start: {
    id: "Start",
    header: "Step 1 – Evident?",
    mainText: "Would the loss of function become evident under normal circumstances to the operating crew?",
    yesNextStep: "Evident",
    noNextStep: "Hidden",
    info: "Answer 'No' for hidden failures. These are protective devices that require another independent failure before they matter, or before we find out that they have failed. Otherwise, answer 'yes'. If a failure takes time to become evident, it still counts as evident.",
  },
  Evident: {
    id: "Evident",
    header: "Step 2 – Safety/Environment?",
    mainText: "Would this failure have safety consequences or breach an environmental standard or regulation?",
    yesNextStep: "ES1",
    noNextStep: "EF1",
    info: "A failure has safety or environmental consequences if there is an intolerable risk that it will kill or injure someone, or breach an environmental standard or regulation",
  },
  Hidden: {
    id: "Hidden",
    header: "Step 2 – Safety/Environment?",
    mainText: "Would this multiple failure have safety consequences or breach an environmental standard or regulation?",
    yesNextStep: "HS1",
    noNextStep: "HF1",
    info: "A failure has safety or environmental consequences if there is an intolerable risk that it will kill or injure someone, or breach an environmental standard or regulation",
  },
  ES1: {
    id: "ES1",
    header: "Step 3 – ES1 On-Condition Task?",
    mainText: "Is an On-Condition Task technically feasible and worth doing?",
    yesNextStep: "AES1",
    noNextStep: "ES2",
    info: "To be technically feasible an on-condition task requires a clear potential failure condition (or a clear warning that the failure is occurring or about to occur). Also, the period between the potential failure and the functional failure (the P-F interval) must be long enough to allow the task to be carried out within this interval, and action to be taken to avoid the consequences of failure.\n\nTo be worth doing, the task must reduce the level of risk to a tolerable level",
  },
  ES2: {
    id: "ES2",
    header: "Step 4 – ES2 Scheduled Overhaul?",
    mainText: "Is a Scheduled Overhaul Task technically feasible and worth doing?",
    yesNextStep: "AES2",
    noNextStep: "ES3",
    info: "To be technically feasible a scheduled overhaul requires there to be an age (calendar time, running time, cycles etc) at which there is a rapid increase in the conditional probability of failure, and most failures should occur after this age. Also, it must be practical to carry out the overhaul within this age and the overhaul should restore the condition to a satisfactory level.\n\nTo be worth doing, the task must reduce the level of risk to a tolerable level",
  },
  ES3: {
    id: "ES3",
    header: "Step 5 – ES3 Scheduled Replacement?",
    mainText: "Is a Scheduled Replacement Task technically feasible and worth doing?",
    yesNextStep: "AES3",
    noNextStep: "ES4",
    info: "To be technically feasible a scheduled replacement requires there to be an age (calendar time, running time, cycles etc) at which there is a rapid increase in the conditional probability of failure, and most failures should occur after this age. Also, it must be practical to carry out the overhaul within this age.\n\nTo be worth doing, the task must reduce the level of risk to a tolerable level",
  },
  ES4: {
    id: "ES4",
    header: "Step 6 – ES4 Redesign?",
    mainText: "Would a Redesign (one-time change) be technically feasible and worth doing?",
    yesNextStep: "AES4",
    noNextStep: "AES5",
    info: "Can a suitable redesign or one-time change (physical design change, training or competence improvement, new, revised or reinforced procedure, spares or contingency) be made to manage this failure mode?\n\nWould the redesign reduce the level of risk to a tolerable level?",
  },
  EF1: {
    id: "EF1",
    header: "Step 3 – EF1 On-Condition Task?",
    mainText: "Is an On-Condition Task technically feasible and worth doing?",
    yesNextStep: "AEF1",
    noNextStep: "EF2",
    info: "To be technically feasible an on-condition task requires a clear potential failure condition (or a clear warning that the failure is occurring or about to occur). Also, the period between the potential failure and the functional failure (the P-F interval) must be long enough to allow the task to be carried out within this interval, and action to be taken to avoid the consequences of failure.\n\nTo be worth doing, over a suitable period, the cost of doing the task must be less than the cost of not doing the task",
  },
  EF2: {
    id: "EF2",
    header: "Step 4 – EF2 Scheduled Overhaul?",
    mainText: "Is a Scheduled Overhaul Task technically feasible and worth doing?",
    yesNextStep: "AEF2",
    noNextStep: "EF3",
    info: "To be technically feasible a scheduled overhaul requires there to be an age (calendar time, running time, cycles etc) at which there is a rapid increase in the conditional probability of failure, and most failures should occur after this age. Also, it must be practical to carry out the overhaul within this age and the overhaul should restore the condition to a satisfactory level.\n\nTo be worth doing, over a suitable period, the cost of doing the task must be less than the cost of not doing the task",
  },
  EF3: {
    id: "EF3",
    header: "Step 5 – EF3 Scheduled Replacement?",
    mainText: "Is a Scheduled Replacement Task technically feasible and worth doing?",
    yesNextStep: "AEF3",
    noNextStep: "EF4",
    info: "To be technically feasible a scheduled replacement requires there to be a life (calendar time, running time, cycles etc) at which there is a rapid increase in the conditional probability of failure, and most failures should occur after this life. Also, it must be practical to carry out the replacement within this life.\n\nTo be worth doing, over a suitable period, the cost of doing the task must be less than the cost of not doing the task",
  },
  EF4: {
    id: "EF4",
    header: "Step 6 – EF4 Reactive Maintenance only?",
    mainText: "Is it cost effective to deal with the failure using reactive maintenance only?",
    yesNextStep: "AEF4",
    noNextStep: "AEF5",
    info: "Would it be cost effective to manage this failure mode with a policy of No Scheduled Maintenance, or would the combination of the cost of the failure and the risk of the failure mean such a policy is too expensive?",
  },
  HS1: {
    id: "HS1",
    header: "Step 3 – HS1 On-Condition Task?",
    mainText: "Is an On-Condition Task technically feasible and worth doing?",
    yesNextStep: "AHS1",
    noNextStep: "HS2",
    info: "To be technically feasible an on-condition task requires a clear potential failure condition (or a clear warning that the failure is occurring or about to occur). Also, the period between the potential failure and the functional failure (the P-F interval) must be long enough to allow the task to be carried out within this interval, and action to be taken to avoid the consequences of failure.\n\nTo be worth doing, the task must reduce the level of risk to a tolerable level",
  },
  HS2: {
    id: "HS2",
    header: "Step 4 – HS2 Scheduled Overhaul?",
    mainText: "Is a Scheduled Overhaul Task technically feasible and worth doing?",
    yesNextStep: "AHS2",
    noNextStep: "HS3",
    info: "To be technically feasible a scheduled overhaul requires there to be an age (calendar time, running time, cycles etc) at which there is a rapid increase in the conditional probability of failure, and most failures should occur after this age. Also, it must be practical to carry out the overhaul within this age and the overhaul should restore the condition to a satisfactory level.\n\nTo be worth doing, the task must reduce the level of risk to a tolerable level",
  },
  HS3: {
    id: "HS3",
    header: "Step 5 – HS3 Scheduled Replacement?",
    mainText: "Is a Scheduled Replacement Task technically feasible and worth doing?",
    yesNextStep: "AHS3",
    noNextStep: "HS4",
    info: "To be technically feasible a scheduled replacement requires there to be a life (calendar time, running time, cycles etc) at which there is a rapid increase in the conditional probability of failure, and most failures should occur after this life. Also, it must be practical to carry out the replacement within this life.\n\nTo be worth doing, the task must reduce the level of risk to a tolerable level",
  },
  HS4: {
    id: "HS4",
    header: "Step 6 – HS4 Failure Finding?",
    mainText: "Would a Failure Finding Task be technically feasible and worth doing?",
    yesNextStep: "AHS4",
    noNextStep: "HS5",
    info: "For Failure-finding be technically feasible, it must be possible to check that the protective device has failed at a suitable interval. This interval is calculated using a suitable formula.\nTo be worth doing, the task must reduce the level of risk to a tolerable level",
  },
  HS5: {
    id: "HS5",
    header: "Step 7 – HS5 Redesign?",
    mainText: "Would a Redesign (one-time change) be technically feasible and worth doing?",
    yesNextStep: "AHS5",
    noNextStep: "AHS6",
    info: "Can a suitable redesign or one-time change (physical design change, training or competence improvement, new, revised or reinforced procedure, spares or contingency) be made to manage this failure mode?\n\nWould the redesign reduce the level of risk to a tolerable level?",
  },
  HF1: {
    id: "HF1",
    header: "Step 3 – HF1 On-Condition Task?",
    mainText: "Is an On-Condition Task technically feasible and worth doing?",
    yesNextStep: "AHF1",
    noNextStep: "HF2",
    info: "To be technically feasible an on-condition task requires a clear potential failure condition (or a clear warning that the failure is occurring or about to occur). Also, the period between the potential failure and the functional failure (the P-F interval) must be long enough to allow the task to be carried out within this interval, and action to be taken to avoid the consequences of failure.\n\nTo be worth doing, over a suitable period, the cost of doing the task must be less than the cost of not doing the task",
  },
  HF2: {
    id: "HF2",
    header: "Step 4 – HF2 Scheduled Overhaul?",
    mainText: "Is a Scheduled Overhaul Task technically feasible and worth doing?",
    yesNextStep: "AHF2",
    noNextStep: "HF3",
    info: "To be technically feasible a scheduled overhaul requires there to be an age (calendar time, running time, cycles etc) at which there is a rapid increase in the conditional probability of failure, and most failures should occur after this age. Also, it must be practical to carry out the overhaul within this age and the overhaul should restore the condition to a satisfactory level.\n\nTo be worth doing, over a suitable period, the cost of doing the task must be less than the cost of not doing the task",
  },
  HF3: {
    id: "HF3",
    header: "Step 5 – HF3 Scheduled Replacement?",
    mainText: "Is a Scheduled Replacement Task technically feasible and worth doing?",
    yesNextStep: "AHF3",
    noNextStep: "HF4",
    info: "To be technically feasible a scheduled replacement requires there to be a life (calendar time, running time, cycles etc) at which there is a rapid increase in the conditional probability of failure, and most failures should occur after this life. Also, it must be practical to carry out the replacement within this life.\n\nTo be worth doing, over a suitable period, the cost of doing the task must be less than the cost of not doing the task",
  },
  HF4: {
    id: "HF4",
    header: "Step 6 – HF4 Failure Finding?",
    mainText: "Is a Failure Finding Task technically feasible and worth doing?",
    yesNextStep: "AHF4",
    noNextStep: "HF5",
    info: "For Failure-finding be technically feasible, it must be possible to check that the protective device has failed at a suitable interval. This interval is calculated using a suitable formula.\n\nTo be worth doing, over a suitable period, the task must reduce the impact on total costs to a satisfactory level.",
  },
  HF5: {
    id: "HF5",
    header: "Step 7 – HF5 Reactive Maintenance only?",
    mainText: "Is it cost effective to deal with the failure using reactive maintenance only?",
    yesNextStep: "AHF5",
    noNextStep: "AHF6",
    info: "Would it be cost effective to manage this failure mode with a policy of No Scheduled Maintenance, or would the combination of the cost of the failure and the risk of the failure mean such a policy is too expensive?",
  },
};

export const answers: Record<string, Answer> = {
  AES1: {
    id: "AES1",
    recommendation: "On-Condition Task",
    explanation: "An On-Condition Task is recommended for this evident failure mode with safety/environmental consequences.",
  },
  AES2: {
    id: "AES2",
    recommendation: "Scheduled Overhaul Task",
    explanation: "A Scheduled Overhaul Task is recommended for this evident failure mode with safety/environmental consequences.",
  },
  AES3: {
    id: "AES3",
    recommendation: "Scheduled Replacement Task",
    explanation: "A Scheduled Replacement Task is recommended for this evident failure mode with safety/environmental consequences.",
  },
  AES4: {
    id: "AES4",
    recommendation: "Redesign",
    explanation: "A Redesign is recommended for this evident failure mode with safety/environmental consequences.",
  },
  AES5: {
    id: "AES5",
    recommendation: "Risk Review",
    explanation: "A Risk Review is recommended for this evident failure mode with safety/environmental consequences.",
  },
  AEF1: {
    id: "AEF1",
    recommendation: "On-Condition Task",
    explanation: "An On-Condition Task is recommended for this evident failure mode with financial consequences.",
  },
  AEF2: {
    id: "AEF2",
    recommendation: "Scheduled Overhaul Task",
    explanation: "A Scheduled Overhaul Task is recommended for this evident failure mode with financial consequences.",
  },
  AEF3: {
    id: "AEF3",
    recommendation: "Scheduled Replacement Task",
    explanation: "A Scheduled Replacement Task is recommended for this evident failure mode with financial consequences.",
  },
  AEF4: {
    id: "AEF4",
    recommendation: "Reactive Maintenance",
    explanation: "Reactive Maintenance is recommended for this evident failure mode with financial consequences.",
  },
  AEF5: {
    id: "AEF5",
    recommendation: "Redesign",
    explanation: "A Redesign is recommended for this evident failure mode with financial consequences.",
  },
  AHS1: {
    id: "AHS1",
    recommendation: "On-Condition Task",
    explanation: "An On-Condition Task is recommended for this hidden failure mode with safety/environmental consequences.",
  },
  AHS2: {
    id: "AHS2",
    recommendation: "Scheduled Overhaul Task",
    explanation: "A Scheduled Overhaul Task is recommended for this hidden failure mode with safety/environmental consequences.",
  },
  AHS3: {
    id: "AHS3",
    recommendation: "Scheduled Replacement Task",
    explanation: "A Scheduled Replacement Task is recommended for this hidden failure mode with safety/environmental consequences.",
  },
  AHS4: {
    id: "AHS4",
    recommendation: "Failure Finding Task",
    explanation: "A Failure Finding Task is recommended for this hidden failure mode with safety/environmental consequences.",
  },
  AHS5: {
    id: "AHS5",
    recommendation: "Redesign",
    explanation: "A Redesign is recommended for this hidden failure mode with safety/environmental consequences.",
  },
  AHS6: {
    id: "AHS6",
    recommendation: "Risk Review",
    explanation: "A Risk Review is recommended for this hidden failure mode with safety/environmental consequences.",
  },
  AHF1: {
    id: "AHF1",
    recommendation: "On-Condition Task",
    explanation: "An On-Condition Task is recommended for this hidden failure mode with financial consequences.",
  },
  AHF2: {
    id: "AHF2",
    recommendation: "Scheduled Overhaul Task",
    explanation: "A Scheduled Overhaul Task is recommended for this hidden failure mode with financial consequences.",
  },
  AHF3: {
    id: "AHF3",
    recommendation: "Scheduled Replacement Task",
    explanation: "A Scheduled Replacement Task is recommended for this hidden failure mode with financial consequences.",
  },
  AHF4: {
    id: "AHF4",
    recommendation: "Failure Finding Task",
    explanation: "A Failure Finding Task is recommended for this hidden failure mode with financial consequences.",
  },
  AHF5: {
    id: "AHF5",
    recommendation: "Reactive Maintenance",
    explanation: "Reactive Maintenance is recommended for this hidden failure mode with financial consequences.",
  },
  AHF6: {
    id: "AHF6",
    recommendation: "Redesign",
    explanation: "A Redesign is recommended for this hidden failure mode with financial consequences.",
  },
};

export const assets: Asset[] = [
  {
    name: "Pump",
    failureModes: ["Cavitation", "Bearing failure", "Seal leakage"],
  },
  {
    name: "Valve",
    failureModes: ["Stuck open", "Stuck closed", "External leakage"],
  },
  {
    name: "Motor",
    failureModes: ["Overheating", "Bearing failure", "Insulation breakdown"],
  },
  {
    name: "Heat Exchanger",
    failureModes: ["Fouling", "Tube leakage", "Corrosion"],
  },
  {
    name: "Compressor",
    failureModes: ["Loss of compression", "Vibration", "Oil contamination"],
  },
];
